server.port=8081

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pago_servicios_db
spring.datasource.username=postgres
spring.datasource.password=Compl1c@do
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history
spring.flyway.schemas=public

# GestoPago
gestopago.base-url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000

# Productos
gestopago.productos.endpoint=/sistema/service/getProductList.do
gestopago.productos.connect-timeout=5000
gestopago.productos.read-timeout=10000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Config Server desactivado
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=5000ms

# Sincronización diaria de productos
#gestopago.productos.sync-cron=0 0 6 * * *
gestopago.productos.sync-cron=0 * * * * *
gestopago.productos.sync-zone=America/Mexico_City